spring.application.name=GameServer
# ????? URL
# allowPublicKeyRetrieval=true ????? MySQL 8.0+ ?????????
spring.datasource.url=jdbc:mysql://localhost:3306/gameserver?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Tokyo

# ????????
spring.datasource.username=root
spring.datasource.password=1236985.

# ?????? (MySQL 8.x ????????)
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate ??
# update: ???? Java ????????????????????
spring.jpa.hibernate.ddl-auto=update
# ?????? SQL ?????????? Java ???????????
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# ??
spring.jackson.date-format=yyyy-MM-dd'T'HH:mm:ss.SSSX

spring.mail.host=smtp.qq.com
spring.mail.port=587
spring.mail.username=yukino1_3@qq.com
spring.mail.password=qlgkebndueeobfif
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Redis ????????? Docker ????????? localhost?
spring.data.redis.host=localhost
spring.data.redis.port=6379

# ????? Redis ????????????
# spring.data.redis.password=

# ?????????????
spring.data.redis.lettuce.pool.max-active=8
spring.data.redis.lettuce.pool.max-idle=8

